### ISSUE TITLE
Manage Arrays for attributes in service-manifest

### ISSUE THREAD

**Issue by mfouilleul** [blablacar/green-garden#37]
The generate failed when we put an array in attributes, for instance:

```
nodes:
  - hostname: "test1"
    ip: "XXX.XXX.XXX.XXX"
    attributes:
      nerve:
        services:
          - svc_name: "name1"
            svc_port: 3333
            zk_path: "/services/test/name1"
            check_interval: 2
            weight: 200
```

The error is `error=json: unsupported type: map[interface {}]interface {}`
