### ISSUE TITLE
Exclude aci from service-manifest

### ISSUE THREAD

**Issue by MattKetmo** [blablacar/green-garden#43]
Add ability to exclude ACIs in the `service-manifest.yml`.

For instance, `pod-foobar` contains `aci-foo`, `aci-bar` and `aci-zabbix`. I'd like to:

``` yaml
containers:
  - pod-foobar
exclude:
  - aci-zabbit # this will remove pod-foobar_aci-zabbit from the {{.acis}} variable
```
